"""add character detail fields

Revision ID: 1c91d97a83da
Revises: a435d1018fd9
Create Date: 2026-08-17 11:27:29.090335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c91d97a83da'
down_revision: Union[str, Sequence[str], None] = 'a435d1018fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('avatar_large_url', sa.String(length=255), nullable=True))
    op.add_column('characters', sa.Column('origin_story', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('timeline', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'timeline')
    op.drop_column('characters', 'origin_story')
    op.drop_column('characters', 'avatar_large_url')
    # ### end Alembic commands ###
