"""create chronicle events table

Revision ID: 4037005217c4
Revises: 152a5a44adc1
Create Date: 2026-08-20 16:10:51.238300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4037005217c4'
down_revision: Union[str, Sequence[str], None] = '152a5a44adc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chronicle_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronicle_events_year'), 'chronicle_events', ['year'], unique=False)
    chronicle_events = sa.table(
        'chronicle_events',
        sa.column('year', sa.Integer()),
        sa.column('date', sa.String()),
        sa.column('title', sa.String()),
        sa.column('content', sa.Text()),
        sa.column('image_url', sa.String()),
        sa.column('sort_order', sa.Integer()),
    )
    op.bulk_insert(
        chronicle_events,
        [
            {
                'year': 2022,
                'date': '2022-11',
                'title': '哈基米首次出圈：两个笨蛋',
                'content': '社区编年资料将“哈基米”追溯到《赛马娘》中东海帝皇哼唱的片段。2022 年 11 月，一京桥刹那发布《两个笨蛋》，把这段声音与猫咪素材结合，形成首次大范围传播节点。',
                'image_url': None,
                'sort_order': 1,
            },
            {
                'year': 2024,
                'date': '2024-06',
                'title': '孤高曼波带来音乐二创潮',
                'content': '一根华仔发布《孤高曼波》后，哈基米音乐再次出圈。曼波分支的角色原点被资料归为《赛马娘》中的诗歌剧：魔性的“曼波”音频、改编歌与 AI 翻唱让它成为音乐档案的重要入口。',
                'image_url': None,
                'sort_order': 1,
            },
            {
                'year': 2024,
                'date': '2024-09-11',
                'title': '圆头耄耋关键影像出现',
                'content': '《耄耋编年史》记录：账号“白手套&马大旺”上传了一段橘猫录像。圆润头型、固定镜头与强烈表情为后续二创提供了素材，网友逐渐赋予它“圆头耄耋”的人格化称呼。',
                'image_url': None,
                'sort_order': 2,
            },
            {
                'year': 2025,
                'date': '2025-04',
                'title': '耄耋与鼠鼠点燃第三次出圈',
                'content': '圆头耄耋在 2025 年春季爆发，同期鼠鼠也快速走红。鼠鼠的原始图像被资料指向海外博主发布的 Swag Cat，进入中文互联网后被游戏社区、低清动图与夸张表情不断重塑。',
                'image_url': None,
                'sort_order': 1,
            },
            {
                'year': 2025,
                'date': '2025-05-31',
                'title': 'Doro：桃乐丝衍生形态进入档案',
                'content': 'Doro 并非原作角色本身，而是围绕《胜利女神：NIKKE》角色桃乐丝发展出的变形同人形象。粉发、白色小身体与夸张动作使它脱离原作语境，成为独立传播的抽象文化支线。',
                'image_url': None,
                'sort_order': 2,
            },
            {
                'year': 2026,
                'date': '2026-08',
                'title': '基米小站开启系统化收录',
                'content': '基米小站将角色档案、表情包、音乐与文化事件放入同一资料体系。此后管理员可持续写入新节点，公开时间轴会自动按年份扩展。',
                'image_url': None,
                'sort_order': 1,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chronicle_events_year'), table_name='chronicle_events')
    op.drop_table('chronicle_events')
    # ### end Alembic commands ###
