"""add external music source fields

Revision ID: 5300cd38775f
Revises: d6f87c2daf8a
Create Date: 2026-08-21 10:07:48.574327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5300cd38775f'
down_revision: Union[str, Sequence[str], None] = 'd6f87c2daf8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_tracks', sa.Column('source_type', sa.String(length=20), server_default='upload', nullable=False))
    op.add_column('music_tracks', sa.Column('source_author', sa.String(length=100), nullable=True))
    op.alter_column('music_tracks', 'cover_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('music_tracks', 'source_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('submissions', sa.Column('source_type', sa.String(length=20), server_default='upload', nullable=False))
    op.add_column('submissions', sa.Column('source_author', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'source_author')
    op.drop_column('submissions', 'source_type')
    op.alter_column('music_tracks', 'source_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('music_tracks', 'cover_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('music_tracks', 'source_author')
    op.drop_column('music_tracks', 'source_type')
    # ### end Alembic commands ###
