"""add content withdrawal statuses

Revision ID: 94c7d58b99da
Revises: d2fd3d219144
Create Date: 2026-08-21 14:33:06.045355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c7d58b99da'
down_revision: Union[str, Sequence[str], None] = 'd2fd3d219144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.create_index(op.f('ix_memes_status'), 'memes', ['status'], unique=False)
    op.add_column('music_tracks', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.create_index(op.f('ix_music_tracks_status'), 'music_tracks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_tracks_status'), table_name='music_tracks')
    op.drop_column('music_tracks', 'status')
    op.drop_index(op.f('ix_memes_status'), table_name='memes')
    op.drop_column('memes', 'status')
    # ### end Alembic commands ###
