"""add multiple character associations

Revision ID: 9fd467a31e83
Revises: 9d45b4be8ae1
Create Date: 2026-08-17 14:00:40.417272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd467a31e83'
down_revision: Union[str, Sequence[str], None] = '9d45b4be8ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_characters',
    sa.Column('meme_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meme_id', 'character_id')
    )
    op.create_table('music_track_characters',
    sa.Column('music_track_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_track_id'], ['music_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('music_track_id', 'character_id')
    )
    op.create_table('submission_characters',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', 'character_id')
    )

    op.execute(
        sa.text(
            """
            INSERT INTO meme_characters (meme_id, character_id)
            SELECT id, character_id
            FROM memes
            WHERE character_id IS NOT NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO music_track_characters (music_track_id, character_id)
            SELECT id, character_id
            FROM music_tracks
            WHERE character_id IS NOT NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO submission_characters (submission_id, character_id)
            SELECT id, character_id
            FROM submissions
            WHERE character_id IS NOT NULL
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_characters')
    op.drop_table('music_track_characters')
    op.drop_table('meme_characters')
    # ### end Alembic commands ###
