"""remove user nickname

Revision ID: ae41965aef44
Revises: 69e4266c7bca
Create Date: 2026-08-14 16:58:57.590440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ae41965aef44'
down_revision: Union[str, Sequence[str], None] = '69e4266c7bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'nickname',
            sa.String(length=80),
            nullable=False,
            server_default='',
        ),
    )
    # ### end Alembic commands ###
