"""add meme image hash

Revision ID: d2fd3d219144
Revises: 6b893b9b9046
Create Date: 2026-08-21 14:20:16.587136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fd3d219144'
down_revision: Union[str, Sequence[str], None] = '6b893b9b9046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('image_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_memes_image_hash'), 'memes', ['image_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memes_image_hash'), table_name='memes')
    op.drop_column('memes', 'image_hash')
    # ### end Alembic commands ###
