"""add haki records and published submission fields

Revision ID: d3bc49e1bacb
Revises: 1c91d97a83da
Create Date: 2026-08-17 13:44:31.545535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bc49e1bacb'
down_revision: Union[str, Sequence[str], None] = '1c91d97a83da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haki_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_value', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_haki_records_user_id'), 'haki_records', ['user_id'], unique=False)
    op.add_column('submissions', sa.Column('content_id', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('content_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_submissions_content_id'), 'submissions', ['content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_content_id'), table_name='submissions')
    op.drop_column('submissions', 'content_deleted')
    op.drop_column('submissions', 'content_id')
    op.drop_index(op.f('ix_haki_records_user_id'), table_name='haki_records')
    op.drop_table('haki_records')
    # ### end Alembic commands ###
