"""add favorites and haki rules

Revision ID: d6f87c2daf8a
Revises: 4037005217c4
Create Date: 2026-08-20 17:27:55.543948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f87c2daf8a'
down_revision: Union[str, Sequence[str], None] = '4037005217c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haki_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_haki_rules_action'), 'haki_rules', ['action'], unique=True)
    op.bulk_insert(
        sa.table(
            'haki_rules',
            sa.column('action', sa.String()),
            sa.column('value', sa.Integer()),
        ),
        [
            {'action': 'upload_meme', 'value': 10},
            {'action': 'upload_music', 'value': 10},
            {'action': 'favorite_get', 'value': 5},
            {'action': 'download_get', 'value': 1},
            {'action': 'admin_pick', 'value': 50},
        ],
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_favorites_user_target')
    )
    op.create_index(op.f('ix_favorites_target_id'), 'favorites', ['target_id'], unique=False)
    op.create_index(op.f('ix_favorites_target_type'), 'favorites', ['target_type'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.add_column('haki_records', sa.Column('action', sa.String(length=50), nullable=True))
    op.add_column('haki_records', sa.Column('target_type', sa.String(length=20), nullable=True))
    op.add_column('haki_records', sa.Column('target_id', sa.Integer(), nullable=True))
    op.add_column('haki_records', sa.Column('source_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_haki_records_action'), 'haki_records', ['action'], unique=False)
    op.create_index(op.f('ix_haki_records_source_user_id'), 'haki_records', ['source_user_id'], unique=False)
    op.create_index(op.f('ix_haki_records_target_id'), 'haki_records', ['target_id'], unique=False)
    op.create_foreign_key(
        'fk_haki_records_source_user_id_users',
        'haki_records',
        'users',
        ['source_user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_haki_records_source_user_id_users', 'haki_records', type_='foreignkey')
    op.drop_index(op.f('ix_haki_records_target_id'), table_name='haki_records')
    op.drop_index(op.f('ix_haki_records_source_user_id'), table_name='haki_records')
    op.drop_index(op.f('ix_haki_records_action'), table_name='haki_records')
    op.drop_column('haki_records', 'source_user_id')
    op.drop_column('haki_records', 'target_id')
    op.drop_column('haki_records', 'target_type')
    op.drop_column('haki_records', 'action')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_target_type'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_target_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_haki_rules_action'), table_name='haki_rules')
    op.drop_table('haki_rules')
    # ### end Alembic commands ###
